package dll.constanst;

/**
 * @描述:
 * @作者: REN
 * @时间: 2019/1/3 15:28
 */
/**
 * JNA Wrapper for library <b>sdk_def</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SDKDef {
    //public static final String JNA_LIBRARY_NAME = "sdk_def";
    //public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Sdk_defLibrary.JNA_LIBRARY_NAME);
    //public static final Sdk_defLibrary INSTANCE = (Sdk_defLibrary)Native.loadLibrary(Sdk_defLibrary.JNA_LIBRARY_NAME, Sdk_defLibrary.class);
    /** enum values */
    public static interface tagIMOSThruLineDirection {
        /**
         * < \u987a\u65f6\u9488<br>
         * <i>native declaration : line 752</i>
         */
        public static final int IMOS_THRU_LINE_DIRECTION_CLOCKWISE = 0;
        /**
         * < \u9006\u65f6\u9488<br>
         * <i>native declaration : line 753</i>
         */
        public static final int IMOS_THRU_LINE_DIRECTION_ANTICLOCKWISE = 1;
        /**
         * < \u53cc\u5411<br>
         * <i>native declaration : line 754</i>
         */
        public static final int IMOS_THRU_LINE_DIRECTION_ALL = 2;
        /** <i>native declaration : line 756</i> */
        public static final int IMOS_THRU_LINE_DIRECTION_MAX = 3;
        /** <i>native declaration : line 757</i> */
        public static final long IMOS_THRU_LINE_DIRECTION_INVALID = 0XFFFFFFFFL;
    };
    /** enum values */
    public static interface tagIMOSAreaDirection {
        /**
         * < In<br>
         * <i>native declaration : line 767</i>
         */
        public static final int IMOS_AREA_DIRECTION_IN = 0;
        /**
         * < Out<br>
         * <i>native declaration : line 768</i>
         */
        public static final int IMOS_AREA_DIRECTION_OUT = 1;
        /**
         * < \u53cc\u5411<br>
         * <i>native declaration : line 769</i>
         */
        public static final int IMOS_AREA_DIRECTION_ALL = 2;
        /** <i>native declaration : line 771</i> */
        public static final int IMOS_AREA_DIRECTION_MAX = 3;
        /** <i>native declaration : line 772</i> */
        public static final long IMOS_AREA_DIRECTION_INVALID = 0XFFFFFFFFL;
    };
    /** enum values */
    public static interface tagOptionName {
        /**
         * < CC\u7684\u670d\u52a1\u5668\u5730\u5740, \u5bf9\u5e94\u7ed3\u6784 : (CHAR *)<br>
         * <i>native declaration : line 782</i>
         */
        public static final int OPTION_NAME_CC_SERVER_ADDR = 0;
        /**
         * < IMOSROOT\u73af\u5883\u53d8\u91cf, \u5bf9\u5e94\u7ed3\u6784 : (CHAR *)<br>
         * <i>native declaration : line 783</i>
         */
        public static final int OPTION_IMOS_ROOT_PATH = 1;
        /**
         * < \u534f\u8bae\u7684\u7aef\u53e3\u8303\u56f4, \u5bf9\u5e94\u7ed3\u6784 : (PORT_RANGE_S *)<br>
         * <i>native declaration : line 784</i>
         */
        public static final int OPTION_PROTOCOL_PORT_RANGE = 2;
        /**
         * < \u5a92\u4f53\u6d41\u7684\u7aef\u53e3\u8303\u56f4,\u5bf9\u5e94\u7ed3\u6784 : (PORT_RANGE_S *)<br>
         * <i>native declaration : line 785</i>
         */
        public static final int OPTION_MEDIA_PORT_RANGE = 3;
        /**
         * < IMG\u7684\u670d\u52a1\u5668\u7aef\u53e3, \u5bf9\u5e94\u7ed3\u6784 : (USHORT)<br>
         * <i>native declaration : line 786</i>
         */
        public static final int OPTION_NAME_SERVER_IMG_PORT = 4;
        /** <i>native declaration : line 788</i> */
        public static final int OPTION_NAME_MAX = 5;
        /** <i>native declaration : line 789</i> */
        public static final long OPTION_NAME_INVALID = 0XFFFFFFFFL;
    };
    /** enum values */
    public static interface tagCallBackProcType {
        /**
         * < \u8bbe\u5907\u72b6\u6001\uff0c\u5bf9\u5e94\u7ed3\u6784 : AS_STAPUSH_UI_S<br>
         * <i>native declaration : line 809</i>
         */
        public static final int PROC_TYPE_DEV_STATUS = 0;
        /**
         * < \u544a\u8b66\uff0c\u5bf9\u5e94\u7ed3\u6784 : AS_ALARMPUSH_UI_S<br>
         * <i>native declaration : line 810</i>
         */
        public static final int PROC_TYPE_ALARM = 1;
        /**
         * < \u5171\u4eab\u6444\u50cf\u673a\uff0c\u5bf9\u5e94\u7ed3\u6784 : AS_DEVPUSH_UI_S<br>
         * <i>native declaration : line 811</i>
         */
        public static final int PROC_TYPE_DEV_CAM_SHEAR = 2;
        /**
         * < \u5b9e\u51b5\u88ab\u62a2\u5360\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_MONITOR_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 812</i>
         */
        public static final int PROC_TYPE_MONITOR_BE_REAVED = 3;
        /**
         * < \u8f6e\u5207\u88ab\u62a2\u5360\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_SWITCH_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 813</i>
         */
        public static final int PROC_TYPE_SWITCH_BE_REAVED = 4;
        /**
         * < \u5b9e\u51b5\u88ab\u505c\u6b62\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_MONITOR_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 814</i>
         */
        public static final int PROC_TYPE_MONITOR_BE_STOPPED = 5;
        /**
         * < \u8f6e\u5207\u88ab\u505c\u6b62\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_SWITCH_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 815</i>
         */
        public static final int PROC_TYPE_SWITCH_BE_STOPPED = 6;
        /**
         * < \u8bed\u97f3\u88ab\u62a2\u5360\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_VOCSRV_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 816</i>
         */
        public static final int PROC_TYPE_VOCSRV_BE_REAVED = 7;
        /**
         * < \u4e91\u53f0\u4e8b\u4ef6\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_PTZ_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 817</i>
         */
        public static final int PROC_TYPE_PTZ_EVENT = 8;
        /**
         * < \u6545\u969c\u5904\u7406\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_NOTIFY_UI_TRB_EVENT_PROC_S<br>
         * <i>native declaration : line 818</i>
         */
        public static final int PROC_TYPE_TRB_PROC = 9;
        /**
         * < \u6545\u969c\u6062\u590d\u4e1a\u52a1\u5efa\u7acb\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_NOTIFY_UI_SRV_SETUP_S<br>
         * <i>native declaration : line 819</i>
         */
        public static final int PROC_TYPE_SRV_SETUP = 10;
        /**
         * < \u544a\u8b66\u8054\u52a8\u5230XP\u7a97\u683c\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_NOTIFY_UI_SRV_SETUP_S<br>
         * <i>native declaration : line 820</i>
         */
        public static final int PROC_TYPE_XP_ALARM_SETUP = 11;
        /**
         * < \u9000\u51fa\u767b\u9646\uff0c\u5bf9\u5e94\u7ed3\u6784 :\u65e0<br>
         * <i>native declaration : line 822</i>
         */
        public static final int PROC_TYPE_LOGOUT = 12;
        /**
         * < \u5a92\u4f53\u53c2\u6570\u6539\u53d8\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_NOTIFY_UI_MEDIA_PARAM_CHANGE_PROC_S<br>
         * <i>native declaration : line 824</i>
         */
        public static final int PROC_TYPE_MEDIA_PARAM_CHANGE = 13;
        /**
         * < \u5916\u57df\u72b6\u6001\uff0c\u5bf9\u5e94\u7ed3\u6784 : AS_EXDOMAIN_STAPUSH_UI_S<br>
         * <i>native declaration : line 826</i>
         */
        public static final int PROC_TYPE_EXDOMAIN_STATUS = 14;
        /**
         * < \u4fe1\u606f\u5907\u4efd\u5b8c\u6210\u901a\u77e5, \u5bf9\u5e94\u7ed3\u6784 : CS_BACKUP_FINISH_INFO_S<br>
         * <i>native declaration : line 828</i>
         */
        public static final int PROC_TYPE_BACKUP_DATA_FINISH = 15;
        /**
         * < \u900f\u660e\u901a\u9053\u4e8b\u4ef6\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_TL_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 830</i>
         */
        public static final int PROC_TYPE_TL_EVENT = 16;
        /**
         * < \u7ec4\u663e\u793a\u5355\u5143\u4e8b\u4ef6\u901a\u77e5, \u5bf9\u5e94\u7ed3\u6784 : CS_NOTIFY_SALVO_UNIT_EVENT_S<br>
         * <i>native declaration : line 832</i>
         */
        public static final int PROC_TYPE_SALVO_UNIT_EVENT = 17;
        /**
         * < \u7ec4\u5207\u4e1a\u52a1\u4e8b\u4ef6\u901a\u77e5, \u5bf9\u5e94\u7ed3\u6784 : CS_NOTIFY_UI_SALVO_EVENT_S<br>
         * <i>native declaration : line 833</i>
         */
        public static final int PROC_TYPE_SALVO_EVENT = 18;
        /**
         * < \u901a\u77e5UI\u542f\u52a8\u7ec4\u8f6e\u5de1\u7684\u7ec4\u663e\u793a, \u5bf9\u5e94\u7ed3\u6784: CS_NOTIFY_START_XP_SALVO_S<br>
         * <i>native declaration : line 834</i>
         */
        public static final int PROC_TYPE_START_XP_SALVO = 19;
        /**
         * < \u901a\u77e5\u56de\u653e\u4e0a\u5899\u88ab\u62a2\u5360\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aCS_VODWALL_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 836</i>
         */
        public static final int PROC_TYPE_VODWALL_BE_REAVED = 20;
        /**
         * < \u901a\u77e5\u56de\u653e\u4e0a\u5899\u88ab\u505c\u6b62\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aCS_VODWALL_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 837</i>
         */
        public static final int PROC_TYPE_VODWALL_BE_STOPPED = 21;
        /**
         * < \u56de\u653e\u88ab\u62a2\u5360\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_VOD_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 839</i>
         */
        public static final int PROC_TYPE_VOD_BE_REAVED = 22;
        /**
         * < \u57df\u95f4\u540c\u6b65\u7684\u7ed3\u679c\uff0c\u5bf9\u5e94\u7ed3\u6784 : AS_DOMAIN_SYN_PUSHUI_S<br>
         * <i>native declaration : line 841</i>
         */
        public static final int PROC_TYPE_DOMAIN_SYN_RESULT = 23;
        /**
         * < \u5ba2\u6237\u7aef\u8bed\u97f3\u8bf7\u6c42\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_VOC_REQ_NOTIFY_S<br>
         * <i>native declaration : line 843</i>
         */
        public static final int PROC_TYPE_VOC_REQ = 24;
        /**
         * < \u8bed\u97f3\u4e1a\u52a1\u72b6\u6001\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_VOC_STATE_NOTIFY_S<br>
         * <i>native declaration : line 844</i>
         */
        public static final int PROC_TYPE_VOC_STATE_NOTIFY = 25;
        /**
         * < \u9884\u6848\u544a\u8b66\u53d8\u5316\u4e0a\u62a5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aPLAN_ALARM_CHG_PUSH_UI_S<br>
         * <i>native declaration : line 846</i>
         */
        public static final int PROC_TYPE_PLAN_ALARM_CHG_REPORT = 26;
        /**
         * < \u7cfb\u7edf\u7ea7\u522b\u4fe1\u606f\u53d8\u5316\u4e0a\u62a5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aEVENT_SECURITY_CHG_PUSH_UI_S<br>
         * <i>native declaration : line 847</i>
         */
        public static final int PROC_TYPE_EVENT_SECURITY_CHG_REPORT = 27;
        /**
         * < \u901a\u77e5\u4eba\u673aPreview\u7528\u6237OSD\u53d8\u66f4\uff0c\u5bf9\u5e94\u7ed3\u6784: AS_NOTIFY_OSD_NAME_UI_S<br>
         * <i>native declaration : line 848</i>
         */
        public static final int PROC_TYPE_OSD_NAME_CHANGED = 30;
        /**
         * < \u901a\u77e5\u4eba\u673aPreview\u7528\u6237\u906e\u6321\u533a\u57df\u53d8\u66f4\uff0c\u5bf9\u5e94\u7ed3\u6784: AS_NOTIFY_EC_MASK_AREA_UI_S<br>
         * <i>native declaration : line 849</i>
         */
        public static final int PROC_TYPE_MASK_AREA_CHANGED = 31;
        /**
         * < \u4e91\u53f0\u72b6\u6001\u53d8\u66f4\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : CS_PTZ_STATUS_NOTIFY_S<br>
         * <i>native declaration : line 851</i>
         */
        public static final int PROC_TYPE_PTZ_STATUS_EVENT = 32;
        /**
         * < \u5220\u9664\u5916\u57df\u7ed3\u679c\uff0c\u5bf9\u5e94\u7ed3\u6784: AS_DEL_EXDOMAIN_PUSH_UI_S<br>
         * <i>native declaration : line 852</i>
         */
        public static final int PROC_TYPE_DEL_EXDOMAIN_RESULT = 33;
        /**
         * < \u901a\u77e5UI\u542f\u52a8\u81ea\u52a8\u5e03\u5c40\u7ec4\u8f6e\u5de1, \u5bf9\u5e94\u7ed3\u6784: CS_NOTIFY_START_XP_AUTOSALVO_S<br>
         * <i>native declaration : line 854</i>
         */
        public static final int PROC_TYPE_START_XP_AUTOSALVO = 34;
        /**
         * < \u900f\u660e\u901a\u9053\u4e0a\u884c\u900f\u4f20\u6d88\u606f\u7ed9\u7b2c\u4e09\u65b9<br>
         * <i>native declaration : line 857</i>
         */
        public static final int PROC_TYPE_GET_CHANNEL_MSG_FROM_CS_TO_UI = 35;
        /**
         * < \u901a\u77e5\u5b9e\u65f6\u8f66\u8f86\u4fe1\u606f\uff0c\u5bf9\u5e94\u7ed3\u6784:VEHICLE_REAL_TIME_DATA_S<br>
         * <i>native declaration : line 861</i>
         */
        public static final int PROC_TYPE_VEHICLE_DATA = 90;
        /**
         * < \u901a\u77e5\u5b9e\u65f6\u8f66\u8f86\u62a5\u8b66\uff0c\u5bf9\u5e94\u7ed3\u6784:VEHICLE_ALARM_DATA_S<br>
         * <i>native declaration : line 862</i>
         */
        public static final int PROC_TYPE_VEHICLE_ALARM_DATA = 91;
        /**
         * < \u901a\u77e5GIS\u8bbe\u5907\u72b6\u6001\u53d8\u5316\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aDEVICE_GIS_STATUS_DATA_S<br>
         * <i>native declaration : line 863</i>
         */
        public static final int PROC_TYPE_GIS_DEV_STATUS = 92;
        /**
         * < \u7535\u5b50\u516c\u544a\u53d8\u5316\u4e0a\u62a5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aELEC_BULLETIN_PUSH_UI_S<br>
         * <i>native declaration : line 865</i>
         */
        public static final int PROC_TYPE_ELEC_BULLETIN_CHANGE = 93;
        /**
         * < \u53d1\u8a00\u7533\u8bf7\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aCONF_SITE_INFO_EX_S<br>
         * <i>native declaration : line 870</i>
         */
        public static final int PROC_TYPE_ACCEPT_SPEAK_YESORNO = 100;
        /**
         * < \u4f1a\u8bae\u72b6\u6001\u6539\u53d8\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aCONF_STATUS_INFO_EX_S \u5982\u679c\u662f\u5468\u671f\u4f1a\u8bae\u4e14\u975e\u6700\u540e\u4e00\u4e2a\u5468\u671f\uff0c\u4e0a\u62a5\u4f1a\u8bae\u672a\u5f00\u59cb/\u5176\u5b83\u4e0a\u62a5\u4f1a\u8bae\u5df2\u7ecf\u7ed3\u675f<br>
         * <i>native declaration : line 871</i>
         */
        public static final int PROC_TYPE_CONF_STATUS_CHANGE = 101;
        /**
         * < \u8bbe\u5907\u7f16\u7801\u6539\u53d8\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aDEVICE_CODE_CHANGE_INFO_EX_S<br>
         * <i>native declaration : line 872</i>
         */
        public static final int PROC_TYPE_DEVICE_CODE_CHANGE = 102;
        /**
         * < \u7ec8\u7aef\u8bbe\u5907\u66f4\u65b0\u4fe1\u606f\uff0c \u5f53\u5b58\u5728\u8bbe\u5907\u65b0\u589e\u3001\u5220\u9664\u65f6\uff0c \u4e0a\u62a5\u66f4\u65b0\u6d88\u606f\uff0c \u5bf9\u5e94\u7684\u7ed3\u6784 \uff1aDEVICE_CHANGE_INFO_EX_S<br>
         * <i>native declaration : line 873</i>
         */
        public static final int PROC_TYPE_DEVICE_CHANGE = 103;
        /**
         * < \u4fee\u6539\u7ec8\u7aef\u6d88\u606f\uff0c \u5bf9\u5e94\u7684\u7ed3\u6784 \uff1aMODIFY_TERM_REP_EX_S<br>
         * <i>native declaration : line 874</i>
         */
        public static final int PROC_TYPE_MODIFY_TERM = 104;
        /**
         * < \u5f53\u524d\u4e3b\u5e2d\u53d1\u751f\u6539\u53d8\uff0c \u4e3b\u5e2d\u4f1a\u573a\u91ca\u653e\u5219\u4f1a\u573a\u7f16\u7801\u4e3a\u7a7a\u3002\u5bf9\u5e94\u7684\u7ed3\u6784 \uff1aCONF_SITE_INFO_EX_S<br>
         * <i>native declaration : line 875</i>
         */
        public static final int PROC_TYPE_CHAIR_CHANGE = 105;
        /**
         * < \u5f53\u524d\u53d1\u8a00\u4eba\u53d1\u751f\u6539\u53d8\uff0c \u5bf9\u5e94\u7684\u7ed3\u6784 \uff1aCONF_SITE_INFO_EX_S<br>
         * <i>native declaration : line 876</i>
         */
        public static final int PROC_TYPE_SPEAKER_CHANGE = 106;
        /**
         * < \u4f1a\u573a\u7ec8\u7aef\u72b6\u6001\u6539\u53d8\uff0c \u5bf9\u5e94\u7684\u7ed3\u6784 \uff1aTERM_STATUS_CHANGE_EX_S<br>
         * <i>native declaration : line 877</i>
         */
        public static final int PROC_TYPE_TERM_STATUS_CHANGE = 107;
        /**
         * < \u5ef6\u8fdf\u4f1a\u8bae\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aDELAY_CONF_INFO_EX_S<br>
         * <i>native declaration : line 878</i>
         */
        public static final int PROC_TYPE_DELAY_CONF = 108;
        /**
         * < \u4e0a\u62a5\u5e7f\u64ad\u4f1a\u573a\uff0c \u4e3b\u5e2d\u3001\u4e3b\u573a\u89c2\u770b\u4f1a\u573a \u5bf9\u5e94\u7684\u7ed3\u6784 \uff1a MC_SYNCHRONIZE_WITH_WEB_EX_S<br>
         * <i>native declaration : line 879</i>
         */
        public static final int PROC_TYPE_SYNCHRONIZE_WITH_WEB = 109;
        /**
         * < MCU\u5907\u4efd\u901a\u77e5\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aBACKUP_MCU_REPORT_S<br>
         * <i>native declaration : line 880</i>
         */
        public static final int PROC_TYPE_MCU_BACKUP_CHANGE_TO_MASTER = 110;
        /**
         * < \u5f53\u524d\u8f85\u6d41\u53d1\u9001\u8005\u53d8\u5316\u901a\u77e5\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aCONF_SEND_ROLE_SITE_CHANGE_S<br>
         * <i>native declaration : line 881</i>
         */
        public static final int PROC_TYPE_SEND_ROLE_SITE_CHANGE = 111;
        /**
         * < \u591a\u753b\u9762\u81ea\u52a8\u5207\u6362\u503c\u6539\u53d8\u901a\u77e5\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aCONF_AUTOMULTIPIC_CHANGE_S<br>
         * <i>native declaration : line 882</i>
         */
        public static final int PROC_TYPE_AUTOMULTIPIC_CHANGE = 112;
        /**
         * < \u8bbe\u7f6e\u753b\u9762\u8f6e\u8be2\u6a21\u5f0f\u6539\u53d8\u901a\u77e5\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aCONF_SET_TURN_BROADCAST_CHANGE_S<br>
         * <i>native declaration : line 883</i>
         */
        public static final int PROC_TYPE_SET_TURN_BROADCAST_CHANGE = 113;
        /**
         * < \u8bbe\u7f6e\u753b\u9762\u6a21\u5f0f\u6539\u53d8\u901a\u77e5\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aCONF_SET_PIC_MODE_CHANGE_S<br>
         * <i>native declaration : line 884</i>
         */
        public static final int PROC_TYPE_SET_PIC_MODE_CHANGE = 114;
        /**
         * < MCU\u540c\u6b65\u72b6\u6001\u6539\u53d8\u901a\u77e5\uff0c \u5bf9\u5e94\u7ed3\u6784 \uff1aMCU_SYNC_STATUS_CHANGE_S<br>
         * <i>native declaration : line 885</i>
         */
        public static final int PROC_TYPE_MCU_SYNC_STATUS_CHANGE = 115;
        /**
         * < \u5f53\u524d\u5b9e\u9645\u5e7f\u64ad\u4f1a\u573a\u6539\u53d8\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aCUR_BROADCAST_INFO_EX_S<br>
         * <i>native declaration : line 886</i>
         */
        public static final int PROC_TYPE_CUR_BROADCAST_CHANGE = 116;
        /**
         * < \u5f53\u524d\u4e3b\u5e2d\u6216\u4e3b\u573a\u5b9e\u9645\u89c2\u770b\u7684\u4f1a\u573a\u6539\u53d8\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aCUR_CHAIR_BROWSE_INFO_EX_S<br>
         * <i>native declaration : line 887</i>
         */
        public static final int PROC_TYPE_CUR_CHAIR_BROWSE_CHANGE = 117;
        /**
         * < \u5f53\u524dFECC\u63a7\u5236\u8005\u6216\u88ab\u63a7\u8005\u53d8\u5316\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aCONF_FECC_CHANGE_S<br>
         * <i>native declaration : line 888</i>
         */
        public static final int PROC_TYPE_CONF_FECC_CHANGE = 118;
        /**
         * < \u5f53\u524d\u4f1a\u8bae\u4e2dMCU\u5907\u4efd\u53d8\u5316\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aCONF_MCU_BACKUP_CHANGE_S<br>
         * <i>native declaration : line 889</i>
         */
        public static final int PROC_TYPE_CONF_MCU_BACKUP_CHANGE = 119;
        /**
         * < \u547c\u53eb\u4f1a\u573a\u7ed3\u679c\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aCALL_SITE_INFO_EX_S<br>
         * <i>native declaration : line 890</i>
         */
        public static final int PROC_TYPE_CALL_SITE_RESULT = 120;
        /**
         * < GK\u6ce8\u518c\u7ed3\u679c\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aGK_REG_STATE_INFO_EX_S<br>
         * <i>native declaration : line 891</i>
         */
        public static final int PROC_TYPE_GK_REG_STATE = 121;
        /**
         * < \u7ec8\u7aef\u4f1a\u8bdd\u72b6\u6001\uff0c\u5bf9\u5e94\u7ed3\u6784\uff1aMG_SESSION_STATUS_EX_S<br>
         * <i>native declaration : line 892</i>
         */
        public static final int PROC_TYPE_MG_SESSION_STATUS_CHANGE = 122;
        /**
         * < \u5b58\u50a8\u8d44\u6e90\u88ab\u91ca\u653e\uff0c\u5bf9\u5e94\u7ed3\u6784 : FREE_STORE_RES_SUCCEED_S<br>
         * <i>native declaration : line 893</i>
         */
        public static final int PROC_TYPE_FREE_STORE_RES_SUCCEED = 123;
        /**
         * < \u5a92\u4f53\u72b6\u6001\u901a\u77e5\u6d88\u606f\uff0c\u5bf9\u5e94\u7ed3\u6784 : MEDIA_STATUS_NOTIFY_S<br>
         * <i>native declaration : line 894</i>
         */
        public static final int PROC_TYPE_MEDIA_STATUS_NOTIFY = 124;
        /**
         * < \u544a\u8b66\u8054\u52a8\u5230\u8bed\u97f3\u5bf9\u8bb2\u901a\u77e5\uff0c\u5bf9\u5e94\u7ed3\u6784 : ALARM_LINKAGE_VOCTALK_TO_UI_S<br>
         * <i>native declaration : line 896</i>
         */
        public static final int PROC_TYPE_ALARM_LINKAGE_VOCTALK = 125;
        /**
         * <\u4eba\u673a\u7ec4\u5207\u8f93\u51fa\u7aef\u53e3\u57fa\u672c\u4fe1\u606f\u6539\u53d8.\u5bf9\u5e94\u7ed3\u6784\u4f53MMI_VOUT_INFO_FOR_ECR_S<br>
         * <i>native declaration : line 900</i>
         */
        public static final int PROC_TYPE_MMI_VOUT_INFO_CHANGE = 400;
        /**
         * <\u4eba\u673a\u7ec4\u5207\u9884\u89c8\u7a97\u683c\u6444\u50cf\u673a\u5e8f\u5217\u4fe1\u606f\u6539\u53d8, \u5bf9\u5e94\u7ed3\u6784\u4f53: MMI_VOUT_WINLIST_INFO_FOR_ECR_S<br>
         * <i>native declaration : line 901</i>
         */
        public static final int PROC_TYPE_MMI_VOUT_WINLIST_CHANGE = 401;
        /**
         * <\u865a\u62df\u901a\u9053\u57fa\u672c\u4fe1\u606f\u6539\u53d8\uff0c\u5bf9\u5e94\u7ed3\u6784\u4f53VIRTUAL_CHANNEL_BIND_STATUS_S<br>
         * <i>native declaration : line 902</i>
         */
        public static final int PROC_TYPE_VIRTUAL_CHANNEL_STATUS_CHANGE = 402;
        /**
         * <\u865a\u62df\u901a\u9053\u5206\u8fa8\u7387/\u5e27\u7387\u6539\u53d8\uff0c\u5bf9\u5e94\u7ed3\u6784\u4f53VIRTUAL_CHANNEL_BIND_STATUS_S<br>
         * <i>native declaration : line 905</i>
         */
        public static final int PROC_TYPE_VIRTUAL_CHANNEL_INFO_CHANGE = 403;
        /**
         * < \u68c0\u67e5\u9501\u5b9a\u7a7a\u95f4\u901a\u77e5\u6d88\u606f\uff0c\u5bf9\u5e94\u7ed3\u6784 : AS_SM_LOCK_SPACE_NOTIFY_S<br>
         * <i>native declaration : line 908</i>
         */
        public static final int PROC_TYPE_LOCK_SPACE_NOTIFY = 404;
        /**
         * < \u6444\u50cf\u673a\u4e0a\u7ebf\u91cd\u4e0b\u53d1\u901a\u77e5\u6d88\u606f\uff0c\u5bf9\u5e94\u7ed3\u6784 : AS_SM_LOCK_FAILURE_NOTIFY_S<br>
         * <i>native declaration : line 909</i>
         */
        public static final int PROC_TYPE_LOCK_FAILURE_NOTIFY = 405;
        /**
         * <\u7535\u89c6\u5899\u573a\u666f\u8f6e\u8be2\u4fe1\u606f\uff0c\u5bf9\u5e94\u7ed3\u6784\u4f53CS_TVWALL_POLL_INFO_NOTIFY_S<br>
         * <i>native declaration : line 912</i>
         */
        public static final int PROC_TYPE_TV_WALL_POLL_INFO_NOTIFY = 406;
        /**
         * < \u7528\u6237\u767b\u9646\u62a2\u5360\u901a\u77e5\u6d88\u606f\uff0c\u5bf9\u5e94\u7ed3\u6784\u4f53: LOGIN_REAVE_NOTIFY_S<br>
         * <i>native declaration : line 915</i>
         */
        public static final int PROC_TYPE_USER_LOGIN_REAVE_NOTIFY = 407;
        /**
         * < \u4ea4\u901a\u4e8b\u4ef6\uff0c\u5bf9\u5e94\u7ed3\u6784 : TMS_TRAFFIC_EVENT_S<br>
         * <i>native declaration : line 917</i>
         */
        public static final int PROC_TYPE_TRAFFIC_EVENT = 408;
        /**
         * < \u56de\u8c03\u51fd\u6570\u5904\u7406\u4fe1\u606f\u7c7b\u578b\u6700\u5927\u503c<br>
         * <i>native declaration : line 919</i>
         */
        public static final int PROC_TYPE_MAX = 409;
        /**
         * < \u65e0\u6548\u503c<br>
         * <i>native declaration : line 920</i>
         */
        public static final long PROC_TYPE_INVALID = 0xFFFFFFFFL;
    };
    /** enum values */
    public static interface tagPtzNotifyUIEventType {
        /**
         * \u4e91\u53f0\u8fde\u63a5\u7a7a\u95f2\u8d85\u65f6 \u8fde\u63a5\u88ab\u91ca\u653e<br>
         * <i>native declaration : line 926</i>
         */
        public static final int PTZ_NOTIFY_TYPE_RELEASE_TIME_OUT = 0;
        /**
         * \u4e91\u53f0\u88ab\u5f3a\u5360\uff0c\u8fde\u63a5\u91ca\u653e<br>
         * <i>native declaration : line 927</i>
         */
        public static final int PTZ_NOTIFY_TYPE_REAVED = 1;
        /**
         * \u4e91\u53f0\u6545\u969c\uff0c\u8fde\u63a5\u91ca\u653e<br>
         * <i>native declaration : line 928</i>
         */
        public static final int PTZ_NOTIFY_TYPE_TROUBLE = 2;
        /**
         * \u7528\u6237\u65e0\u4e91\u53f0\u63a7\u5236\u6743\u9650<br>
         * <i>native declaration : line 929</i>
         */
        public static final int PTZ_NOTIFY_TYPE_USER_HAS_NO_AUTHORITY = 3;
        /**
         * \u7528\u6237\u6743\u9650\u4f4e<br>
         * <i>native declaration : line 930</i>
         */
        public static final int PTZ_NOTIFY_TYPE_PTZ_USER_HAS_LOWER_AUTHORITY = 4;
        /**
         * \u4e91\u53f0\u88ab\u5176\u4ed6\u7528\u6237\u9501\u5b9a<br>
         * <i>native declaration : line 931</i>
         */
        public static final int PTZ_NOTIFY_TYPE_PTZ_HAS_LOCKED_BY_OTHER = 5;
        /**
         * \u63a7\u5236\u5757\u5df2\u6ee1<br>
         * <i>native declaration : line 933</i>
         */
        public static final int PTZ_NOTIFY_TYPE_PTZ_CCB_FULL = 6;
        /** <i>native declaration : line 934</i> */
        public static final int PTZ_NOTIFY_TYPE_MAX = 7;
        /** <i>native declaration : line 935</i> */
        public static final long PTZ_NOTIFY_TYPE_INVALID = 0xFFFFFFFFL;
    };
    /** enum values */
    public static interface tagSalvoUnitNotifyUIEventType {
        /**
         * \u7ec4\u663e\u793a\u5355\u5143\u5efa\u7acb\u5b9e\u51b5\u5931\u8d25<br>
         * <i>native declaration : line 942</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_START_FAIL = 0;
        /**
         * \u7ec4\u663e\u793a\u5355\u5143\u7684\u5b9e\u51b5\u88ab\u62a2\u5360<br>
         * <i>native declaration : line 943</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_BE_REAVED = 1;
        /**
         * \u76f8\u540c\u7684\u7ec4\u663e\u793a\u5355\u5143\u7684\u5b9e\u51b5\u5df2\u5b58\u5728<br>
         * <i>native declaration : line 944</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_SAME_EXIST = 2;
        /**
         * \u76f8\u540c\u7684\u7ec4\u663e\u793a\u5355\u5143\u7684\u5b9e\u51b5\u6b63\u5728\u5efa\u7acb<br>
         * <i>native declaration : line 945</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_SAME_CREATING = 3;
        /**
         * \u6545\u969c\u5f15\u8d77\u7ec4\u663e\u793a\u5355\u5143\u5b9e\u51b5\u91ca\u653e<br>
         * <i>native declaration : line 946</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_TROUBLE = 4;
        /**
         * \u7ec4\u663e\u793a\u5355\u5143\u6062\u590d\u5b9e\u51b5<br>
         * <i>native declaration : line 947</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_RESUME_SUCC = 5;
        /**
         * \u7ec4\u663e\u793a\u4fee\u6539\u5f15\u8d77\u5355\u5143\u5b9e\u51b5\u91ca\u653e<br>
         * <i>native declaration : line 948</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_RES_MODIFY = 6;
        /**
         * \u7528\u6237\u505c\u6b62\u7ec4\u663e\u793a\u5355\u5143<br>
         * <i>native declaration : line 949</i>
         */
        public static final int SALVO_UNIT_NOTIFY_TYPE_USER_STOP = 7;
        /** <i>native declaration : line 951</i> */
        public static final int SALVO_UNIT_NOTIFY_TYPE_MAX = 8;
        /** <i>native declaration : line 952</i> */
        public static final long SALVO_UNIT_NOTIFY_TYPE_INVALID = 0xFFFFFFFFL;
    };
    /** enum values */
    public static interface tagSalvoNotifyEventType {
        /**
         * \u7ec4\u663e\u793a\u4e1a\u52a1\u88ab\u505c\u6b62<br>
         * <i>native declaration : line 959</i>
         */
        public static final int NOTIFY_TYPE_SALVO_BE_STOPPED = 0;
        /**
         * \u7ec4\u663e\u793a\u4e1a\u52a1\u88ab\u62a2\u5360<br>
         * <i>native declaration : line 960</i>
         */
        public static final int NOTIFY_TYPE_SALVO_BE_REAVED = 1;
        /**
         * \u7ec4\u8f6e\u5de1\u4e1a\u52a1\u88ab\u505c\u6b62<br>
         * <i>native declaration : line 961</i>
         */
        public static final int NOTIFY_TYPE_GROUPSALVO_BE_STOPPED = 2;
        /**
         * \u7ec4\u8f6e\u5de1\u4e1a\u52a1\u88ab\u62a2\u5360<br>
         * <i>native declaration : line 962</i>
         */
        public static final int NOTIFY_TYPE_GROUPSALVO_BE_REAVED = 3;
        /**
         * \u7ec4\u8f6e\u5de1\u5207\u6362\u505c\u6b62\u7ec4\u663e\u793a<br>
         * <i>native declaration : line 963</i>
         */
        public static final int NOTIFY_TYPE_GROUPSALVO_STOP_SALVO_PER_TIME = 4;
        /**
         * \u7ec4\u663e\u793a\u4e1a\u52a1\u4e2d\u6240\u6709\u5b9e\u51b5\u5f85\u6062\u590d<br>
         * <i>native declaration : line 964</i>
         */
        public static final int NOTIFY_TYPE_SALVO_ALL_MON_UNACTIVE = 5;
        /** <i>native declaration : line 966</i> */
        public static final int NOTIFY_TYPE_MAX = 6;
        /** <i>native declaration : line 967</i> */
        public static final long NOTIFY_TYPE_INVALID = 0xFFFFFFFFL;
    };
    public static final String A8_BASE_PICTURE_PATH = (String)"/mnt/syncdata/resftp/A8/BASEPIC/";
    public static final String A8_EDID_PATH = (String)"/mnt/syncdata/resftp/A8/EDID/";
    public static final int A8_EDID_SIZE = (int)128;
    public static final int A8_EDID_MAX_SIZE = (int)256;
    public static final int CS_TVWALL_SCENE_ID = (int)99;
    public static final int TVWALL_SCENE_MAX_NUM = (int)64;
    public static final String TVWALL_DEFAULT_CODE = (String)"tvwall";
    public static final String WINDOW_DEFAULT_CODE = (String)"window";
    public static final String CAMERA_DEFAULT_CODE = (String)"cam";
    public static final String SCREEN_DEFAULT_CODE = (String)"screen";
    public static final String TVWALL_SCENE_GROUP_DEFAULT_CODE = (String)"scenegroup";
    public static final String A8_TVWALL_DISABLE_CODE = (String)"DISABLE_TVWALL_CODE";
    public static final String A8_INVILD_SCREEN_CODE = (String)"INVALID_SCREEN_CODE";
    public static final String A8_INVILD_CAMERA_CODE = (String)"INVALID_CAMERA_CODE";
    public static final String A8_INVILD_SWITCH_RES_CODE = (String)"INVALID_SWITCH_RES_CODE";
    public static final String A8_INVILD_POLL_RES_CODE = (String)"INVALID_POLL_RES_CODE";
    public static final String MM_SIP_KEY_MESSAGE = (String)"Message";
    public static final String MM_SIP_KEY_COMMAND = (String)"Command";
    public static final String MM_SIP_KEY_COMMAND_VALUE = (String)"CMD_ALARM_DATA";
    public static final String MM_SIP_KEY_TYPE = (String)"Type";
    public static final String MM_SIP_KEY_TYPE_VALUE = (String)"Req";
    public static final String MM_SIP_KEY_VARIABLE = (String)"Variable";
    public static final String MM_SIP_KEY_WINDOW = (String)"Window";
    public static final String MM_SIP_KEY_SPLIT = (String)"Split";
    public static final String MM_SIP_KEY_ROAM = (String)"Roam";
    public static final String MM_SIP_KEY_STACK = (String)"Stack";
    public static final String MM_SIP_KEY_MOSAIC = (String)"Mosaic";
    public static final String MM_SIP_KEY_BASEMAP = (String)"Basemap";
    public static final String MM_SIP_KEY_VLED = (String)"VLed";
    public static final String MM_SIP_KEY_TRANSPARENCY = (String)"Transparency";
    public static final String MM_SIP_KEY_ARBITRARILY = (String)"Arbitrarily";
    public static final String MM_SIP_KEY_BASEMAPSIZE = (String)"BasemapSize";
    public static final String MM_SIP_KEY_RESOLUTION = (String)"Resolution";
    public static final String XWARE_REG_XML_NODE_MAX_TVWALL_NUM = (String)"MaxTVWallsNums";
    public static final String XWARE_REG_XML_NODE_MAX_SCENES_NUM = (String)"MaxScenesNums";
    public static final String XWARE_REG_XML_NODE_MAX_ROW_NUM = (String)"MaxRowNums";
    public static final String XWARE_REG_XML_NODE_MAX_COL_NUM = (String)"MaxColNums";
    public static final String XWARE_REG_XML_NODE_SUP_VIDEO_FOR = (String)"VideoFormats";
    public static final String XWARE_REG_XML_NODE_MAX_WIN_NUM = (String)"MaxWinNums";
    public static final String XWARE_REG_XML_NODE_MAX_SCREEN_WIN = (String)"MaxPerScreenWinAreas";
    public static final String XWARE_REG_XML_NODE_MAX_PER_WIN_PANE_NUM = (String)"MaxPerWinPaneNums";
    public static final String XWARE_REG_XML_NODE_MIN_WIN_WIDTH = (String)"MinWinWidth";
    public static final String XWARE_REG_XML_NODE_MIN_WIN_HEIGHT = (String)"MinWinHeight";
    public static final String XWARE_REG_XML_NODE_MAX_BASEMAP_NUM = (String)"MaxBaseMapNums";
    public static final String XWARE_REG_XML_NODE_MAX_PERSCENE_BASEMAP_NUM = (String)"MaxPerSceneBaseMapNums";
    public static final String XWARE_REG_XML_NODE_MAX_BASEMAP_WIDTH = (String)"MaxBaseMapWidth";
    public static final String XWARE_REG_XML_NODE_MAX_BASEMAP_HEIGHT = (String)"MaxBaseMapHeight";
    public static final String XWARE_REG_XML_NODE_MAX_BASEMAP_SIZE = (String)"MaxBaseMapSize";
    public static final String XWARE_REG_XML_NODE_MAX_PERSCENE_VIR_LED_NUM = (String)"MaxPerSceneVLEDNums";
    public static final String XWARE_REG_XML_NODE_MAX_VIR_LED_ROW = (String)"MaxVLEDRows";
    public static final String XWARE_REG_XML_NODE_MAX_VIR_LED_CHAR = (String)"MaxVLEDChars";
    public static final String XWARE_REG_XML_NODE_MAX_SEQ_RES_NUM = (String)"MaxSeqRSrcNums";
    public static final String XWARE_REG_XML_NODE_MAX_PANE_SEQ_NUM = (String)"MaxPaneSeqNums";
    public static final String XWARE_REG_XML_NODE_MAX_WIN_SEQ_NUM = (String)"MaxWinSeqNums";
    public static final String XWARE_REG_XML_NODE_MAX_SCENE_SEQ_NUM = (String)"MaxSceneSeqNums";
    public static final String XWARE_REG_XML_NODE_IS_SUP_BACK_TO_SHOW = (String)"CanBacktoShow";
    public static final String XWARE_REG_XML_NODE_WIN_CAP = (String)"WinCaps";
    public static final String XWARE_REG_XML_NODE_PANE_CAP = (String)"PaneCaps";
    public static final String XWARE_REG_XML_NODE_WIN_ROAM_CAP = (String)"WinRoamingCaps";
    public static final String XWARE_REG_XML_NODE_IS_SUP_OVERLAY = (String)"CanOverlay";
    public static final String XWARE_REG_XML_NODE_IS_SUP_SET_TRAN = (String)"CanSetTrans";
    public static final String XWARE_REG_XML_NODE_ABSRACT = (String)"Abstract";
    public static final String XWARE_REG_XML_NODE_SUP_PANE_TYPE = (String)"SupportPaneTypes";
    public static final int IMOS_OPTION_BUFFER_LEN_MIN = (int)1;
    public static final int IMOS_OPTION_BUFFER_LEN_MAX = (int)64;
    public static final int IMOS_MONITOR_MAXNUM_PER_WALL = (int)256;
    public static final int IMOS_ALARM_STORE_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_VOCTALK_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_TVWALL_MONITOR_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_CENTER_STORE_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_PRESET_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_SCREENLIVE_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_MONITORLIVE_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_GIS_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_SWITCHOUT_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_BACKUP_ACTION_MAXNUM = (int)16;
    public static final int IMOS_ALARM_ACTION_RECEIVER_MAXNUM = (int)300;
    public static final int IMOS_ALARM_BUZZER_ACTION_MAXNUM = (int)1;
    public static final int IMOS_TRANSPARENT_SERIAL_NUM = (int)2;
    public static final int IMOS_SWITCH_CAM_MAXNUM = (int)32;
    public static final int IMOS_SWITCH_CAM_MAXNUM_V2 = (int)512;
    public static final int IMOS_CRUISE_PATH_PRESET_MAX_COUNT = (int)32;
    public static final int IMOS_ARRAY_SLOT_MAXNUM = (int)10;
    public static final int IMOS_MASK_AREA_MAXNUM_III = (int)3;
    public static final int IMOS_MASK_AREA_MAXNUM_I = (int)1;
    public static final int IMOS_COVER_AREA_MAXNUM = (int)4;
    public static final int IMOS_NTP_SERVER_MAXNUM = (int)3;
    public static final int IMOS_GIS_FOR_ALARM_SRC_MAX_NUM = (int)5;
    public static final int IMOS_CONTRACT_ID = (int)32;
    public static final int IMOS_LICENSE_SERIALS_NUM = (int)256;
    public static final int IMOS_LICENSE_SERVICE_TYPE_NUM = (int)20;
    public static final int IMOS_PAGE_QUERY_ROW_MAX_NUM = (int)200;
    public static final int IMOS_ONCE_SHARE_RES_MAXNUM = (int)1;
    public static final int IMOS_MAX_CAMERA_NUM_PER_EC = (int)64;
    public static final int IMOS_MAX_SCREEN_NUM_PER_DC = (int)16;
    public static final int IMOS_INVALID_CHANNEL_NO = (int)0xFF;
    public static final int IMOS_XP_WIN_MAX_NUM = (int)128;
    public static final int IMOS_QUERY_DATA_MAX_LEN = (int)64;
    public static final int IMOS_QUERY_ITEM_MAX_NUM = (int)16;
    public static final int IMOS_MAX_EXTERNAL_DOMAIN_NUM = (int)2048;
    public static final int IMOS_MAX_USER_ROLES_NUM = (int)16;
    public static final int IMOS_MAX_NOTIFY_LEN = (int)4096;
    public static final int IMOS_DEV_STATUS_MAX_NUM = (int)4;
    public static final int IMOS_DISPLAY_MAXNUM_PER_LAYOUT = (int)256;
    public static final int IMOS_DISPLAY_MAXNUM_PER_SALVO = (int)256;
    public static final int IMOS_SCENE_MAXNUM_RES = (int)1;
    public static final int IMOS_RES_NUM_MAX_PER_GROUP = (int)256;
    public static final int IMOS_COMMON_SWITCH_RES_MAXNUM = (int)256;
    public static final int IMOS_AUTOPOLL_CAMERA_RES_MAXNUM = (int)5000;
    public static final int IMOS_AUTOPOLL_WINDOW_RES_MAXNUM = (int)480;
    public static final int IMOS_AUTOPOLL_WINDOWSPLIT_MAXNUM = (int)(480 * 16);
    public static final int IMOS_GIS_MAX_HOTZONE_NUM_PER_MAP = (int)32;
    public static final int IMOS_GIS_MAX_ICON_NUM_PER_MAP = (int)2048;
    public static final int IMOS_MAX_GIS_MAP_PARAM_NUM = (int)1;
    public static final int IMOS_SYS_PARAM_MAX_NUM = (int)128;
    public static final int IMOS_EVENT_ENABLE_ADD_MAX_NUM = (int)1024;
    public static final int IMOS_EVENT_TYPE_REL_MAX_NUM = (int)128;
    public static final int NIC_COUNT_MAX = (int)4;
    public static final int ONVIF_FLOAT_LEN = (int)48;
    public static final int ONVIF_URL_LEN = (int)256;
    public static final int ONVIF_OSD_TEXT_MAX_LEN = (int)256;
    public static final int ONVIF_OSD_MAX_NUM = (int)8;
    public static final int ONVIF_OSD_DATE_FORMAT_LEN = (int)32;
    public static final int ONVIF_OSD_DATE_FORMAT_MAX_NUM = (int)8;
    public static final int ONVIF_OSD_TEXT_STRING_TYPE_MAX_LEN = (int)32;
    public static final int ONVIF_OSD_TEXT_STRING_TYPE_MAX_NUM = (int)8;
    public static final int ONVIF_OSD_TIME_FORMAT_LEN = (int)32;
    public static final int ONVIF_OSD_TIME_FORMAT_MAX = (int)4;
    public static final int ONVIF_OSD_COLOR_MAX_NUM = (int)16;
    public static final int ONVIF_OSD_COLOR_RANGE_MAX_NUM = (int)16;
    public static final int ONVIF_OSD_IMAGE_PATH_MAX_NUM = (int)16;
    public static final int ONVIF_OSD_POS_TYPE_MAX_LEN = (int)32;
    public static final int ONVIF_OSD_POS_TYPE_MAX_NUM = (int)8;
    public static final int ONVIF_ACTIVE_CELLS_MAX_LEN = (int)512;
    public static final int ONVIF_ITEM_LEN = (int)64;
    public static final int ONVIF_ATTRIBUTE_LEN = (int)64;
    public static final int ONVIF_NAME_LEN = (int)64;
    public static final int ONVIF_TYPE_LEN = (int)64;
    public static final int ONVIF_VIDEO_ENCODER_MAX_NUM = (int)16;
    public static final int ONVIF_VIDEO_ENCODER_NAME_LEN = (int)64;
    public static final int ONVIF_VIDEO_ENCODER_TOKEN_LEN = (int)64;
    public static final int ONVIF_VIDEO_RESOLUTION_MAX_NUM = (int)16;
    public static final int ONVIF_TIME_LEN = (int)32;
    public static final int ONVIF_IPADDR_LEN = (int)64;
    public static final int ONVIF_AUDIO_ENCODER_MAX_NUM = (int)4;
    public static final int ONVIF_AUDIO_OPTIONS_MAX_NUM = (int)8;
    public static final int ONVIF_AUDIO_OPTIONS_BIT_RATE_MAX_NUM = (int)8;
    public static final int ONVIF_AUDIO_OPTIONS_SAMPLE_RATE_MAX_NUM = (int)8;
    public static final String IMOS_MANUFACTURER_TYPE_VMISC = (String)"H3C VM/ISC";
    public static final String IMOS_MANUFACTURER_TYPE_VMISC_V2 = (String)"VM/ISC";
    public static final String IMOS_MANUFACTURER_TYPE_DA = (String)"H3C DA";
    public static final String IMOS_MANUFACTURER_TYPE_CURRENCY_DA = (String)"DA";
    public static final String IMOS_MANUFACTURER_TYPE_OTHER = (String)"Other";
    public static final String IMOS_MANUFACTURER_TYPE_PL = (String)"Aproud PL";
    public static final String IMOS_MANUFACTURER_TYPE_PLS = (String)"Aproud PL-S";
    public static final String IMOS_MANUFACTURER_TYPE_ECRHF = (String)"H3C ECR-HF";
    public static final String IMOS_MANUFACTURER_TYPE_BOCOM = (String)"BOCOM";
    public static final String IMOS_MANUFACTURER_TYPE_DABK = (String)"DABackup";
    public static final String IMOS_PTZ_PROTOCOL_TYPE_INTERNAL = (String)"INTERNAL-PTZ";
    public static final String IMOS_SDK_CLIB_INVALID_IP_ADDRESS = (String)"N/A";
    public static final String IMOS_SDK_INITIATE_INVALID_IP_ADDRESS = (String)"0.0.0.0";
    public static final String IMOS_SDK_MU_CLIB_MODULE_NAME = (String)"VM";
    public static final int IMOS_EMAIL_NOTIFICATION_NUMBER = (int)3;
    public static final int IMOS_HD_MAX_SITE_NAME_LEN = (int)31;
    public static final int IMOS_SITE_NAME_LEN = (int)48;
    public static final int IMOS_HD_MAX_CONF_NAME_LEN = (int)31;
    public static final int IMOS_CONF_NAME_LEN = (int)48;
    public static final int IMOS_HD_MAX_AUDIO_PROTOCOL_NUM = (int)20;
    public static final int IMOS_HD_MAX_BANNER_LEN = (int)43;
    public static final int IMOS_BANNER_LEN = (int)66;
    public static final int IMOS_HD_MAX_CONF_ALIAS_LEN = (int)31;
    public static final int IMOS_CONF_ALIAS_LEN = (int)(31 + 1);
    public static final int IMOS_HD_MAX_SITE_PER_CONF_NUM = (int)256;
    public static final int IMOS_HD_MAX_SUBPIC_NUM = (int)64;
    public static final int IMOS_HD_MAX_VIDEO_FORMAT_NUM = (int)32;
    public static final int IMOS_HD_MAX_VIDEO_FRAMERATE_NUM = (int)7;
    public static final int IMOS_HD_MAX_VIDEO_PROTOCOL_NUM = (int)4;
    public static final int IMOS_HD_MAX_VIDEO_RATE_NUM = (int)8;
    public static final int IMOS_HD_MAX_SIM_CAP_NUM = (int)8;
    public static final int IMOS_MC_MAX_CONF_CYCLE_TABLE_COUNT = (int)10;
    public static final int IMOS_MC_MAX_CONF_PWD_LEN = (int)11;
    public static final int IMOS_CONF_PWD_LEN = (int)(11 + 1);
    public static final int IMOS_MC_MAX_LAN_NET_NUM = (int)4;
    public static final int IMOS_HD_MAX_NETCARD_NAME_LEN = (int)31;
    public static final int IMOS_NETCARD_NAME_LEN = (int)48;
    public static final int IMOS_MC_MAX_MCU_NAME_LEN = (int)31;
    public static final int IMOS_MCU_NAME_LEN = (int)(31 + 1);
    public static final int IMOS_MC_MAX_MCU_IP_NUM = (int)4;
    public static final int IMOS_MC_MAX_LAN_ROUTE_NUM = (int)20;
    public static final int IMOS_MC_MAX_LAN_ARP_NUM = (int)20;
    public static final int IMOS_MC_MAX_MAC_ADDR_LEN = (int)20;
    public static final int IMOS_HD_MAX_SOFT_VERSION_LEN = (int)255;
    public static final int IMOS_SOFT_VERSION_LEN = (int)(255 + 1);
    public static final int IMOS_HD_MAX_DSP_PER_PLANK = (int)15;
    public static final int IMOS_HD_MAX_DSP_NUM_PER_CONF = (int)4;
    public static final int IMOS_HD_MAX_EMAIL_NAME_LEN = (int)63;
    public static final int IMOS_MC_MAX_WATCH_SITE_NUM = (int)9;
    public static final int IMOS_HD_VIDEO_OUT_NUM = (int)(4);
    public static final int IMOS_HD_VERSION_LEN = (int)(32);
    public static final int IMOS_HD_MAX_USER_NUM = (int)(32);
    public static final int IMOS_HD_MAX_CAM_PRE_NUM = (int)(20);
    public static final int IMOS_HD_MAX_NAME_LENGTH = (int)(32);
    public static final int IMOS_HD_MAX_IP_LENGTH = (int)(32);
    public static final int IMOS_HD_MAX_PATH_LENGTH = (int)(100);
    public static final int IMOS_HD_MAX_PASSWORD_LENGTH = (int)(32);
    public static final int IMOS_HD_MAX_PRIVATE_NET_COUNT = (int)(4);
    public static final int IMOS_HD_MAX_MAC_DISPLAYLENGTH = (int)(17);
    public static final int IMOS_TITLE_MAXNUM = (int)(2);
    public static final int IMOS_TITLE_LEN = (int)(2404);
    public static final int IMOS_MAX_CONTACTS_IN_CONF = (int)(512);
    public static final int IMOS_COMPONENT_MAX_NUM = (int)(50);
    public static final int IMOS_MAX_SITE_LIVE_NUM = (int)(240);
    public static final int IMOS_MAX_MULTI_ADDR_NUM = (int)(8);
    public static final int IMOS_MC_MAX_BITRATE_ADAPT_COUNT = (int)(3);
    public static final int IMOS_MAX_MCU_IN_CONF = (int)(16);
    public static final int IMOS_MAX_TERM_IN_CONF = (int)(1024);
    public static final int IMOS_TRANSPARENT_IP_NUM = (int)1;
    public static final int MAX_VOCBRD_CAM_NUM = (int)128;
    public static final int MAX_PTZ_SPEED = (int)9;
    public static final int IMOS_PROC_NAME_MAX_LEN = (int)32;
    public static final int IMOS_DEFAULT_NUM_OF_STREAM_BYPASS = (int)1024;
    public static final int IMOS_MAX_TASK_NUM = (int)(16);
    public static final int IMOS_ALARM_ACTION_TRAN_MAXNUM = (int)(300);
    public static final int IMOS_MAX_TRIGGER_NUM = (int)(10);
    public static final int IMOS_MAX_NEW_ALARM_NUM = (int)(1);
    public static final int IMOS_ALARM_ACTION_PLAN_MAXNUM = (int)(1);
    public static final int IMOS_TYPE_NEW_ALARM = (int)(65534);
    public static final int IMOS_MASK_AREA_MAXNUM_VIII = (int)8;
    public static final int IMOS_VEHICLE_TYPE_MAX_NUM = (int)32;
    public static final int IMOS_PICTURE_SIZE_MAX_LEN = (int)(512 * 1024);
    public static final int IMOS_VIDEO_AREA_TYPE_ROI = (int)3;
    public static final int IMOS_CASE_MAXNUM_PER_SERIESCASE = (int)64;
    public static final int IMOS_FILE_MAXNUM_PER_CASERECORD = (int)8;
    public static final int IMOS_VEHICLE_VIOLATION_MAX_NUM = (int)200;
    public static final int IMOS_DIC_CODE_MAX_NUM = (int)200;
    public static final int IMOS_VEHICLE_DISPOSITION_DOMAIN_MAX_NUM = (int)200;
    public static final int IMOS_VEHICLE_ABNORMAL_ANALYSE_TG_MAX_NUM = (int)200;
    public static final int IMOS_MAP_LINT_POINT_NUM = (int)2;
    public static final int IMOS_MAP_ROAD_POINT_MAX_NUM = (int)64;
    public static final int IMOS_DETECTION_ROAD_SECTION_VIO_CONF_MAX_NUM = (int)32;
    public static final int TMS_MULTI_ADDR_FORWARD_RULE_MAX_NUM = (int)64;
    public static final int IMOS_TOLLGATE_LANE_MAX_NUM = (int)32;
    public static final int IMOS_RES_LIST_MAX_NUM = (int)200;
    public static final String IMOS_SYSTEM_PARAM_BKP_LINK_ENABLE_NAME = (String)"bkp_link_enable_flag";
    public static final String IMOS_SYSTEM_PARAM_BKP_LINK_ENABLE_LOC_RES_NAME = (String)"bkp_link_enable_loc_res_flag";
    public static final int IMOS_IOT_RES_TYPE_MAX_NUM = (int)50;
    public static final int IMOS_TVWALL_SCREN_RES_MAXNUM = (int)48;
    public static final int IMOS_TRUNK_MAXNUM = (int)32;
    public static final int IMOS_TRUNK_CONTENT_MAXNUM = (int)256;
    public static final int IMOS_MAX_3D_COVER_AREA_NUM = (int)8;
}
